import { FormLego } from "@daohaus/form-builder";
import { FIELD } from "@daohaus/moloch-v3-legos";
import { CustomFormLego } from "./fieldConfig";
import { APP_FIELD } from "./fields";
import { ACTION_TX, APP_TX } from "./tx";

const PROPOSAL_SETTINGS_FIELDS = [FIELD.PROPOSAL_EXPIRY, FIELD.PROP_OFFERING];

export const APP_FORM: Record<string, CustomFormLego> = {
  SIGNAL: {
    id: "SIGNAL",
    title: "Signal Form",
    subtitle: "Signal Proposal",
    description: "Ratify on-chain using a DAO proposal.",
    requiredFields: { title: true, description: true },
    log: true,
    tx: APP_TX.POST_SIGNAL,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
      APP_FIELD.TEST_FIELD,
      ...PROPOSAL_SETTINGS_FIELDS,
    ],
  },
  ACCEPT_CONTROL: {
    id: "ACCEPT_CONTROL",
    title: "Accept 0xSplit Control",
    subtitle: "0xSplit Management",
    description: "DAO Proposal",
    requiredFields: { title: true, description: true },
    log: true,
    tx: APP_TX.ACCEPT_CONTROL,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
    ],
  },
  REPLICA_ACCEPT_CONTROL: {
    id: "REPLICA_ACCEPT_CONTROL",
    title: "Accept 0xSplit Control",
    subtitle: "0xSplit Management",
    description: "DAO Proposal",
    requiredFields: { title: true, description: true },
    log: true,
    tx: APP_TX.REPLICA_ACCEPT_CONTROL,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
      APP_FIELD.RELAY_FEE,
      APP_FIELD.CHAINID,
    ],
  },
  TRANSFER_CONTROL: {
    id: "TRANSFER_CONTROL",
    title: "Transfer 0xSplit Control",
    subtitle: "0xSplit Management",
    description: "DAO Proposal",
    requiredFields: { title: true, description: true },
    log: true,
    tx: APP_TX.TRANSFER_CONTROL,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
      APP_FIELD.RECIPIENT
    ],
  },
  REPLICA_TRANSFER_CONTROL: {
    id: "REPLICA_TRANSFER_CONTROL",
    title: "Transfer 0xSplit Control",
    subtitle: "0xSplit Management",
    description: "DAO Proposal",
    requiredFields: { title: true, description: true },
    log: true,
    tx: APP_TX.REPLICA_TRANSFER_CONTROL,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
      APP_FIELD.RECIPIENT,
      APP_FIELD.RELAY_FEE,
      APP_FIELD.CHAINID,
    ],
  },
  CANCEL_TRANSFER: {
    id: "CANCEL_TRANSFER",
    title: "Cancel 0xSplit Transfer",
    subtitle: "0xSplit Management",
    description: "DAO Proposal",
    requiredFields: { title: true, description: true },
    log: true,
    tx: APP_TX.CANCEL_TRANSFER,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK
    ],
  },
  REPLICA_CANCEL_TRANSFER: {
    id: "REPLICA_CANCEL_TRANSFER",
    title: "Cancel 0xSplit Transfer",
    subtitle: "0xSplit Management",
    description: "DAO Proposal",
    requiredFields: { title: true, description: true },
    log: true,
    tx: APP_TX.REPLICA_TRANSFER_CONTROL,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
      APP_FIELD.RELAY_FEE,
      APP_FIELD.CHAINID,
    ],
  },
  BATCH_REPLICA_CLAIM: {
    log: true,
    id: "BATCH_REPLICA_CLAIM",
    title: "Register a new Replica",
    subtitle: "NetworkRegistry Replica",
    description: "Register a Replica deployed on a foreign network and accept the 0xSplit controller role",
    requiredFields: { title: true, description: true },
    tx: APP_TX.BATCH_REPLICA_CLAIM,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
      APP_FIELD.REPLICA,
      APP_FIELD.RELAY_FEE,
      APP_FIELD.CHAINID,
      APP_FIELD.DOMAIN_ID,
      APP_FIELD.REPLICALISTENER,
    ],
  },
  REPLICA_REGISTER: {
    id: "REPLICA_REGISTER",
    title: "Register Replica",
    subtitle: "foreign chain registries",
    description: "Register a replica on a foreign chain",
    requiredFields: { title: true, description: true },
    log: true,
    tx: APP_TX.REPLICA_REGISTER,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
      APP_FIELD.REPLICA,
      APP_FIELD.CHAINID,
    ],
  },
  NEW_MEMBER: {
    id: 'NEW_MEMBER',
    title: 'New Member/s Form',
    subtitle: 'Creates a proposal to register new member/s',
    description: 'DISABLED (Use Bulk Upload instead)',
    requiredFields: { title: true, description: true, members: true, activitymods: true, startdates: true },
    log: true,
    tx: APP_TX.NEW_MEMBER,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
      {... APP_FIELD.CSTEXTAREA, id:'members', label: 'Members'},
      {... APP_FIELD.CSTEXTAREA, id:'activitymods', label: 'Activity Modifier 0-100'},
      {... APP_FIELD.CSTEXTAREA, id:'startdates', label: 'Start Dates (unix epoch)'},
      APP_FIELD.MEMBERLISTENER,
    ],
  },
  EDIT_MEMBER: {
    id: 'EDIT_MEMBER',
    title: 'Edit Member/s Form',
    subtitle: 'Creates a proposal to edit member/s in the regisrty',
    description: 'DISABLED (Use Bulk Upload instead)',
    requiredFields: { title: true, description: true, members: true, activitymods: true },
    log: true,
    tx: APP_TX.EDIT_MEMBER,
    fields: [
      FIELD.TITLE,
      FIELD.DESCRIPTION,
      FIELD.LINK,
      {... APP_FIELD.CSTEXTAREA, id:'members', label: 'Members'},
      {... APP_FIELD.CSTEXTAREA, id:'activitymods', label: 'Activity Modifier 0-100'},
      APP_FIELD.EDITMEMBERLISTENER,
      // ...PROPOSAL_SETTINGS_FIELDS,
    ],
  },
};
